# Use the official PostgreSQL image from Docker Hub
FROM postgres:latest
# Expose the PostgreSQL default port
EXPOSE 5432

#docker build -t my-postgres-image .
#docker run -d -p 5432:5432 --name my-postgres-container -h pgretail_host -e POSTGRES_PASSWORD=sahil my-post-gress-image
#docker exec -it itv_pg psql -U postgres
#DB_NAME=retail_db

# CREATE DATABASE retail_db;
#CREATE DATABASE
# CREATE USER retail_user WITH ENCRYPTED PASSWORD 'sahil';
# GRANT ALL ON DATABASE retail_db TO retail_user;
#GRANT ALL PRIVILEGES ON DATABASE postgres TO postgres;
# \l
# /q
# psql -U postgres
# psql -U retail_user -d retail_db -W

#USED POSTGRES DB ONLY BECAUSE SOME PERMISSION ISSUE COMMING 
#\i /retail_mysql_db/create_db_tables_pg.sql
#\i /retail_mysql_db/load_db_tables_pg.sql